### ISSUE TITLE
Microsoft.Azure.Documents.NotFoundException with Microsoft.Azure.Cosmos 3.17.1

### ISSUE THREAD

**Issue by LastTribunal** [Oriflame/cosmosdb-quartznet#16]
Also tried latest Cosmos: 3.20.1
using your latest Nuget

DocDBTrace Information: 0 : Exception Microsoft.Azure.Documents.NotFoundException: Message: {"Errors":["The read\/write session is not available."]}
ActivityId: c420e5f6-f1cd-4646-a29a-23078a9941cc, Request URI: /apps/b88b41a4-f903-48f0-ae5c-6956bb9269c6/services/5f7173b7-2221-4ec3-9f37-ab9c3ff7ba62/partitions/87683e25-9a4f-4f12-b65f-7740f7be1f53/replicas/132621958839359786s/, RequestStats: , SDK: Windows/10.0.17763 cosmos-netstandard-sdk/3.17.1
at Microsoft.Azure.Documents.TransportClient.ThrowServerException(String resourceAddress, StoreResponse storeResponse, Uri physicalAddress, Guid activityId, DocumentServiceRequest request)
at Microsoft.Azure.Documents.Rntbd.TransportClient.<InvokeStoreAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Azure.Documents.StoreReader.<CompleteActivity>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Azure.Documents.StoreReader.<ReadFromStoreAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at Microsoft.Azure.Documents.StoreReader.<ReadMultipleReplicasInternalAsync>d__12.MoveNext() is thrown while doing readMany

**Comment by LastTribunal** [comment]
Also found this in Comsos
{
    "$type": "Quartz.Spi.CosmosDbJobStore.Entities.PersistentScheduler, Quartz.Spi.CosmosDbJobStore",
    "LastCheckIn": "2021-08-30T20:55:46.2648863+00:00",
    "CheckinInterval": "00:00:07.5000000",
    "InstanceId": "SINGHS-26a642e6-03c3-4a4c-a3fb-d9441f082ccb",
    "id": "Scheduler-eReceiptsScheduler-SINGHS-26a642e6-03c3-4a4c-a3fb-d9441f082ccb",
    "type": "Scheduler",
    "instanceName": "eReceiptsScheduler",
    "_rid": "cj47AOnzziIFAAAAAAAAAA==",
    "_self": "dbs/cj47AA==/colls/cj47AOnzziI=/docs/cj47AOnzziIFAAAAAAAAAA==/",
    "_etag": "\"55002c72-0000-0100-0000-612d45d20000\"",
    "_attachments": "attachments/",
    "_ts": 1630356946
}

"Type" parameter is being used twice, and second time with $prefix, which causes Cosmos UI error

Failed to read item JobDetail-eReceiptsScheduler-cb510056-40b8-46c0-9d00-4566f81740e6-MemberImport - Daily 8/30/2021 4:55:53 PM:
 Illegal characters ['/', '\', '?', '#'] cannot be used in resourceId
